version: '3'

volumes:
  mnf_postgres_data:
    driver: local

services:
  postgres_for_lf8_starter:
    container_name: mnf_postgres_db
    image: postgres:13.3
    volumes:
      - mnf_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mnf_db
      POSTGRES_USER: mnf
      POSTGRES_PASSWORD: secret
    ports:
      - "5436:5432"